localize-repo fixes

diff --git a/localize-repo b/localize-repo
--- a/localize-repo
+++ b/localize-repo
@@ -5,7 +5,7 @@ ME=${0##*/}
 ZDIR=/usr/share/zoneinfo
 SDIR=/etc/apt/sources.list.d
 
-HOST_PREFIXES="NL LA UT OLD_US"
+HOST_PREFIXES="NL LA NZ UT OLD_US"
 HOST_TYPES="AX MX MP"
 US_HOST_LIST="LA UT"
 
@@ -21,6 +21,10 @@ NL_AX_HOST=nl.mxrepo.com/antix
 NL_MP_HOST=nl.mxrepo.com/mepiscr
 NL_MX_HOST=nl.mxrepo.com/mx
 
+NZ_AX_HOST=mx.debian.nz/antix
+NZ_MP_HOST=mx.debian.nz/mepiscr
+NZ_MX_HOST=mx.debian.nz/mx
+
 OLD_US_AX_HOST=antix.daveserver.info
 OLD_US_MP_HOST=main.mepis-deb.org/mepiscr
 OLD_US_MX_HOST=main.mepis-deb.org/mx
@@ -28,15 +32,20 @@ OLD_US_MX_HOST=main.mepis-deb.org/mx
 usage() {
     local ret=${1:-0}
     cat<<Usage
-Usage: $me [options] <timezone|country-code>
+Usage: $me [options] <timezone|country-code|"default">
 
 Update the mirrors in the *.list files under $SDIR/
 with the closest mirrors based on timezone city or two-letter
-country code.
+country code.  If "default" is given then use the timezone
+in the /etc/timezone file.
 
 Options:
+    -c --codes      Only display codes for the servers that would
+                    be used for the given timezone
     -d --dir=<dir>  Use <dir> instead of $SDIR
     -h --help       Show this help
+    -H --hosts      Only show the hosts that would be used for the
+                    given timezone
     -p --pretend    Don't do anything just show what would be done
     -q --quiet      Print less
     -v --verbose    Print more
@@ -46,10 +55,18 @@ Usage
 }
 
 main() {
-    local param val
+    local param val short_stack="cdhHpqv"
     while [ $# -gt 0 -a -n "$1" -a -z "${1##-*}" ]; do
         param=${1#-}
         shift
+
+        case $param in
+            [$short_stack][$short_stack]*)
+                if [ -z "${param//[$short_stack]/}" ]; then
+                    set -- $(echo $param | sed -r 's/([a-zA-Z])/ -\1 /g') "$@"
+                    continue
+                fi;;
+        esac
 
         case $param in
           -dir|d) [ $# -lt 1 ] && fatal "Expected a parameter after: -$param"
@@ -63,9 +80,11 @@ main() {
         esac
 
         case $param in
+           -codes|c) CODES_ONLY=true                   ;;
          -dir=*|d=*) SDIR=$val                         ;;
              -dir|d) SDIR=$val                         ;;
             -help|h) usage                             ;;
+           -hosts|H) HOSTS_ONLY=true                   ;;
          -pretend|p) PRETEND=true                      ;;
            -quiet|q) QUIET=true                        ;;
          -verbose|v) VERBOSE=true                      ;;
@@ -78,6 +97,19 @@ main() {
 
     local tz=$1
 
+    case $tz in
+        */UTC) not_setting $tz ;;
+    esac
+
+    local tz_file=/etc/timezone
+    if [ "$tz" = "default" ]; then
+        test -r $tz_file || fatal "Could not find file $tz_file"
+        read tz 2>/dev/null <$tz_file
+        vsay "Current timezone: $tz"
+    fi
+
+    [ ${#tz} -lt 1 ] && fatal "Timezone or country code too short: $tz"
+
     find_zonetab_file || fatal "Could not find zone.tab file"
 
     case $tz in
@@ -88,8 +120,24 @@ main() {
     local mx_ax_code=$(mx_ax_code $tz)
     local   deb_code=$(deb_code   $tz)
     vsay "deb mirror: $deb_code"
+    [ ${#deb_code} -eq 0 ]   && fatal "No country code found for timezone: $tz"
+    [ ${#mx_ax_code} -eq 0 ] && fatal "No MX/antiX mirrors found for timezone: $tz"
+
+    [ "$CODES_ONLY" ] && echo -e "MX/aX code: $mx_ax_code\n  Deb code: $deb_code"
 
     [ "$mx_ax_code" = "US"  ] && assign_random_server "US" $US_HOST_LIST
+
+    if [ "$HOSTS_ONLY" ]; then
+        local type host
+        for type in $HOST_TYPES; do
+            eval host=\$${mx_ax_code}_${type}_HOST
+            echo " $type: $host"
+        done
+        echo "deb: ftp.$deb_code.debian.org/debian"
+    fi
+
+    [ -n "$CODES_ONLY" -o -n "$HOSTS_ONLY" ] && exit 0
+
 
     # Only update if the mirror is different from the one we want
     SED_EXPR="-e /ftp\.$deb_code\.debian\.org/!s=(http://ftp\.)[a-z][a-z](\.debian.org/debian/)=\1$deb_code\2="
@@ -154,7 +202,7 @@ assign_random_server() {
     local rand=$(($RANDOM % cnt))
     shift $rand
     prefix=$1
-  
+
     for type in $HOST_TYPES; do
         #echo ${targ}_${type}_HOST=\$${prefix}_${type}_HOST
         eval ${targ}_${type}_HOST=\$${prefix}_${type}_HOST
@@ -177,18 +225,98 @@ mx_ax_code() {
     local tz=$1
 
     case $tz in
-        America/*)	    echo US ;;
-        Antarctica/*)	echo US ;;
-        Atlantic/*)	    echo US ;;
-        Australia/*)	echo US ;;
+#        Asia/Colombo)          echo NZ ;;
+#        Asia/Novosibirsk)      echo NZ ;;
+#        Asia/Kathmandu)        echo NZ ;;
+#        Asia/Novokuznetsk)     echo NZ ;;
+#        Asia/Urumqi)           echo NZ ;;
+#        Asia/Kolkata)          echo NZ ;;
+#        Asia/Thimphu)          echo NZ ;;
+#        Asia/Dhaka)            echo NZ ;;
+#        Asia/Hovd)             echo NZ ;;
+#        Asia/Krasnoyarsk)      echo NZ ;;
+#        Asia/Rangoon)          echo NZ ;;
+#        Indian/Cocos)          echo NZ ;;
+#        Asia/Bangkok)          echo NZ ;;
+#        Asia/Kuala_Lumpur)     echo NZ ;;
+#        Asia/Vientiane)        echo NZ ;;
+#        Asia/Singapore)        echo NZ ;;
+#        Asia/Irkutsk)          echo NZ ;;
+#        Asia/Phnom_Penh)       echo NZ ;;
+#        Indian/Christmas)      echo NZ ;;
+#        Asia/Ho_Chi_Minh)      echo NZ ;;
+#        Asia/Jakarta)          echo NZ ;;
+#        Asia/Ulaanbaatar)      echo NZ ;;
+#        Asia/Pontianak)        echo NZ ;;
+#        Asia/Kuching)          echo NZ ;;
+#        Asia/Chita)            echo NZ ;;
+#        Asia/Macau)            echo NZ ;;
+#        Asia/Hong_Kong)        echo NZ ;;
+#        Asia/Choibalsan)       echo NZ ;;
+#        Asia/Brunei)           echo NZ ;;
+#        Australia/Perth)       echo NZ ;;
+#        Asia/Makassar)         echo NZ ;;
+#        Asia/Manila)           echo NZ ;;
+#        Asia/Shanghai)         echo NZ ;;
+#        Asia/Taipei)           echo NZ ;;
+#        Asia/Dili)             echo NZ ;;
+#        Asia/Pyongyang)        echo NZ ;;
+#        Asia/Seoul)            echo NZ ;;
+#        Australia/Eucla)       echo NZ ;;
+#        Asia/Yakutsk)          echo NZ ;;
+#        Australia/Darwin)      echo NZ ;;
+#        Asia/Vladivostok)      echo NZ ;;
+#        Pacific/Palau)         echo NZ ;;
+#        Asia/Khandyga)         echo NZ ;;
+#        Australia/Adelaide)    echo NZ ;;
+#        Asia/Tokyo)            echo NZ ;;
+#        Asia/Jayapura)         echo NZ ;;
+#        Australia/Broken_Hill) echo NZ ;;
+#        Asia/Sakhalin)         echo NZ ;;
+#        Asia/Ust)              echo NZ ;;
+#        Australia/Currie)      echo NZ ;;
+#        Pacific/Guam)          echo NZ ;;
+#        Australia/Melbourne)   echo NZ ;;
+#        Pacific/Saipan)        echo NZ ;;
+#        Pacific/Port_Moresby)  echo NZ ;;
+#        Australia/Hobart)      echo NZ ;;
+#        Australia/Lindeman)    echo NZ ;;
+#        Asia/Magadan)          echo NZ ;;
+#        Australia/Sydney)      echo NZ ;;
+#        Pacific/Chuuk)         echo NZ ;;
+#        Australia/Brisbane)    echo NZ ;;
+#        Asia/Srednekolymsk)    echo NZ ;;
+#        Pacific/Bougainville)  echo NZ ;;
+#        Pacific/Pohnpei)       echo NZ ;;
+#        Asia/Kamchatka)        echo NZ ;;
+#        Australia/Lord_Howe)   echo NZ ;;
+#        Pacific/Guadalcanal)   echo NZ ;;
+#        Pacific/Kosrae)        echo NZ ;;
+#        Pacific/Noumea)        echo NZ ;;
+#        Pacific/Wake)          echo NZ ;;
+#        Pacific/Nauru)         echo NZ ;;
+#        Pacific/Kwajalein)     echo NZ ;;
+#        Pacific/Norfolk)       echo NZ ;;
+#        Pacific/Efate)         echo NZ ;;
+#        Pacific/Majuro)        echo NZ ;;
+#        Pacific/Tarawa)        echo NZ ;;
+#        Pacific/Auckland)      echo NZ ;;
+#        Asia/Anadyr)           echo NZ ;;
+#        Pacific/Fiji)          echo NZ ;;
+#        Pacific/Funafuti)      echo NZ ;;
 
-        Africa/*)	    echo NL ;;
-        Arctic/*)	    echo NL ;;
-        Europe/*)	    echo NL ;;
+        America/*)             echo US ;;
+        Antarctica/*)          echo US ;;
+        Atlantic/*)            echo US ;;
+        Australia/*)           echo US ;;
 
-        Asia/*)	        mx_ax_code_by_longitude $tz ;;
-        Indian/*)	    mx_ax_code_by_longitude $tz ;;
-        Pacific/*)	    mx_ax_code_by_longitude $tz ;;
+        Africa/*)              echo NL ;;
+        Arctic/*)              echo NL ;;
+        Europe/*)              echo NL ;;
+
+        Asia/*)      mx_ax_code_by_longitude $tz ;;
+        Indian/*)    mx_ax_code_by_longitude $tz ;;
+        Pacific/*)   mx_ax_code_by_longitude $tz ;;
     esac
 }
 
@@ -223,7 +351,6 @@ deb_code() {
     local tz=$1
     local ccode=$(tz_to_ccode $tz)
     if [ -z "$ccode" ]; then
-        error "No city code found for timezone: $tz"
         return 2
     fi
 
@@ -318,6 +445,12 @@ error() {
 fatal() {
     echo "$ME Fatal Error: $*" >&2
     exit 5
+}
+
+not_setting() {
+    local tz=$1
+    printf "Not setting repository mirrors based on %s timezone\n"  "$tz"
+    exit 0
 }
 
 vsay() {
